# Generated by Django 2.2.6 on 2022-04-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220406_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
